// Extracts blog posts from the static blog/*.html files into
// frontend/src/data/posts.js (+ post-styles.css), and generates the
// frontend/blog/<slug>.html Vite entry shells preserving each post's SEO head.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const FRONT = join(__dirname, '..');
const BLOG_SRC = join(ROOT, 'blog');
const BLOG_OUT = join(FRONT, 'blog');
const DATA_OUT = join(FRONT, 'src', 'data');
mkdirSync(BLOG_OUT, { recursive: true });
mkdirSync(DATA_OUT, { recursive: true });

const indexMeta = JSON.parse(readFileSync(join(ROOT, 'frontend', 'public', 'assets', 'blog-index.json'), 'utf8'));
const metaBySlug = Object.fromEntries(indexMeta.map((m) => [m.slug, m]));

// balanced innerHTML of <div class="txi-article">
function extractArticle(html) {
  const startTag = '<div class="txi-article">';
  const start = html.indexOf(startTag);
  if (start < 0) throw new Error('no txi-article');
  let depth = 0;
  const re = /<\/?div\b[^>]*>/gi;
  re.lastIndex = start;
  let m;
  while ((m = re.exec(html))) {
    depth += m[0][1] === '/' ? -1 : 1;
    if (depth === 0) {
      return html.slice(start + startTag.length, m.index);
    }
  }
  throw new Error('unbalanced divs');
}

const unesc = (s) => s.replace(/&#x27;/g, "'").replace(/&quot;/g, '"').replace(/&amp;/g, '&');

const files = readdirSync(BLOG_SRC).filter((f) => f.endsWith('.html'));
console.log('post files:', files.length);

const posts = [];
const styleBlocks = []; // distinct per-post <style> variants, in first-seen order
const styleHashes = new Set();

for (const file of files) {
  const slug = file.replace(/\.html$/, '');
  const html = readFileSync(join(BLOG_SRC, file), 'utf8');

  const title = unesc((html.match(/<title>([\s\S]*?)<\/title>/i) || [])[1] || '')
    .replace(/\s*[—–-]\s*Trading Expo India 2027\s*$/, '').trim();
  const meta = unesc((html.match(/<meta name="description" content="([\s\S]*?)">/i) || [])[1] || '');
  const category = unesc((html.match(/<p class="eyebrow">Blog &middot; ([\s\S]*?)<\/p>/i) || [])[1] || '').trim();
  const byline = html.match(/<div class="txi-byline">([\s\S]*?)<\/div>/i);
  const spans = byline ? [...byline[1].matchAll(/<span>([\s\S]*?)<\/span>/gi)].map((x) => unesc(x[1]).replace(/<[^>]+>/g, '').trim()) : [];
  const bylineDate = (spans[2] || '').replace(/^·\s*/, '').trim();
  const readMins = (spans[3] || spans[spans.length - 1] || '').replace(/^·\s*/, '').trim();
  const heroImg = (html.match(/<div class="txi-article">[\s\S]*?<img src="([^"]+)"[^>]*>/) || [])[1] || '';
  const heroAlt = unesc((html.match(/<div class="txi-article">[\s\S]*?<img[^>]*alt="([^"]*)"/) || [])[1] || '');
  const article = extractArticle(html);
  const ldjson = [...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/gi)].map((x) => x[1].trim());

  // shared .txi-* style block — keep the UNION of all variants so reruns
  // never lose rules that only exist in some posts (e.g. .txi-num*).
  const style = (html.match(/<style>([\s\S]*?)<\/style>/i) || [])[1] || '';
  const sh = createHash('md5').update(style).digest('hex');
  if (!styleHashes.has(sh)) { styleHashes.add(sh); if (style.trim()) styleBlocks.push(style); }

  const idx = metaBySlug[slug] || {};
  posts.push({
    slug,
    title,
    meta,
    category: idx.category || category,
    img: idx.img || '',
    read: idx.read || readMins,
    date: idx.date || bylineDate,
    excerpt: idx.excerpt || '',
    file: `blog/${slug}.html`,
    bylineDate,
    heroImg,
    heroAlt,
    ldjson,
    html: article,
  });
}

console.log('distinct <style> blocks:', styleBlocks.length);
// Union all distinct style variants: dedupe identical rules, keep first-seen order.
const seenRules = new Set();
const unionRules = [];
for (const block of styleBlocks) {
  for (const chunk of block.split('}')) {
    const rule = chunk.trim();
    if (!rule) continue;
    if (!seenRules.has(rule)) { seenRules.add(rule); unionRules.push(rule); }
  }
}
const styleCss = unionRules.map((r) => r + '}').join('\n');

writeFileSync(join(FRONT, 'src', 'blog-post-styles.css'),
  `/* Article typography shared by all blog posts — union of the original per-post style blocks. */\n${styleCss}`);
writeFileSync(join(DATA_OUT, 'posts.js'),
  `// Auto-generated by frontend/scripts/extract-posts.mjs — do not hand-edit.\n` +
  `export const posts = ${JSON.stringify(posts, null, 2)};\n` +
  `export const postBySlug = Object.fromEntries(posts.map((p) => [p.slug, p]));\n`);
console.log('posts.js:', posts.length, 'posts');

// ---- generate blog/<slug>.html shells ----
const THEME_INIT = `<script>try{var t=localStorage.getItem("txi-theme");document.documentElement.setAttribute("data-theme",t==="light"||t==="dark"?t:"dark")}catch(e){document.documentElement.setAttribute("data-theme","dark")}</script>`;

for (const p of posts) {
  const src = readFileSync(join(BLOG_SRC, `${p.slug}.html`), 'utf8');
  let head = (src.match(/<head>([\s\S]*?)<\/head>/i) || [])[1] || '';
  head = head
    .replace(/<link[^>]*rel="stylesheet"[^>]*>\s*/gi, '')
    .replace(/<link[^>]*fonts\.googleapis\.com[^>]*>\s*/gi, '')
    .replace(/<link[^>]*fonts\.gstatic\.com[^>]*>\s*/gi, '')
    .replace(/<style>[\s\S]*?<\/style>\s*/i, '');
  const shell = `<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
${THEME_INIT}
${head.trim()}
</head>
<body data-page="post">
<div id="root"></div>
<script type="module" src="/src/entries/post.jsx"></script>
</body>
</html>
`;
  writeFileSync(join(BLOG_OUT, `${p.slug}.html`), shell);
}
console.log('shells written:', posts.length);
